package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"fmt"
	"gateway/graph/model"
	pbconn "gateway/service"
	"strconv"
)

// Query resolver: getUser
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	numId, err := strconv.ParseUint(id, 10, 64)

	resp, err := r.UserClient.GetUser(ctx, &pbconn.GetUserRequest{Id: numId})
	if err != nil {
		return nil, err
	}

	user := resp.User // assuming the field is called "User"
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:    strconv.FormatUint(resp.User.Id, 10),
		Name:  user.Name,
		Email: user.Email,
	}, nil
}

// Query resolver: getPost
func (r *queryResolver) GetPost(ctx context.Context, id string) (*model.Post, error) {
	resp, err := r.PostClient.GetPost(ctx, &pbconn.PostId{Id: id})
	if err != nil {
		return nil, err
	}

	if resp == nil {
		return nil, fmt.Errorf("post not found")
	}

	return &model.Post{
		ID:           resp.Id,
		AuthorID:     resp.AuthorId,
		Text:         resp.Text,
		Visibility:   resp.Visibility,
		CommentCount: resp.CommentCount,
		LikeCount:    resp.LikeCount,
		ShareCount:   resp.ShareCount,
	}, nil
}

// GetConnections is the resolver for the getConnections field.
func (r *queryResolver) GetConnections(ctx context.Context, userID string) ([]*model.UserConnection, error) {
	panic(fmt.Errorf("not implemented: GetConnections - getConnections"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
