// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID           string       `json:"id"`
	AuthorID     string       `json:"author_id"`
	Text         string       `json:"text"`
	Visibility   string       `json:"visibility"`
	Media        []*PostMedia `json:"media,omitempty"`
	CreatedAt    string       `json:"created_at"`
	UpdatedAt    string       `json:"updated_at"`
	CommentCount int32        `json:"comment_count"`
	LikeCount    int32        `json:"like_count"`
	ShareCount   int32        `json:"share_count"`
}

type PostMedia struct {
	URL  string `json:"url"`
	Type string `json:"type"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserConnection struct {
	UserID   string `json:"userId"`
	FriendID string `json:"friendId"`
}
